version: '3.8'
services:
   db:
        image: postgres:15
        container_name: odoo18_db
        environment:
                - POSTGRES_USER=odoo
                - POSTGRES_PASSWORD=odoo
                - POSTGRES_DB=postgres
                - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
                - db-data:/var/lib/postgresql/data/pgdata
        ports:
                - "5433:5432"

   odoo:
        image: odoo:18.0
        container_name: odoo18_web
        command: --dev=all
        ports:
                - "8070:8070"
        depends_on:
                - db
        environment:
                - HOST=db
                - USER=odoo
                - PASSWORD=odoo
        volumes:
                - ./config:/etc/odoo
                - .:/mnt/extra-addons
                - odoo-data:/var/lib/odoo

volumes:
        odoo-data:
        db-data: